### ISSUE TITLE
fingerpori.py throws an uncaught exception every time

### ISSUE THREAD

**Issue by mattikan** [laitalaj/haloobot#10]
@paavohuhtala pls fix

**Comment by laitalaj** [comment]
@mattikan please provide the error message encountered, thank you

**Comment by mattikan** [comment]
"I tried to do my job but then encountered an uncaught exception! It happened somewhere around haloobot/utils/fingerpori.py, line 9. Paavo Huhtala was the last to touch that. I'm doing my best >:"
Additionally, here's the traceback provided by @laitalaj
![photo_2018-12-13_18-21-21](https://user-images.githubusercontent.com/16340245/49952143-1578f200-ff04-11e8-9e09-c2e5bf46a973.jpg)
The sooner @paavohuhtala can get on this, the sooner we can get back to enjoying our daily fingerporis
fingers crossed

**Comment by laitalaj** [comment]
Thank you. @paavohuhtala pls fix
